security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
            our_db_provider:
               entity:
                   class: App\Entity\User
                   property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: default
            logout: true

    access_control:
          - { path: ^/paymaster/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/users/*, roles: ROLE_ADMIN }
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/, roles: ROLE_MANAGER }


    role_hierarchy:
              ROLE_SUPERVISOR:  ROLE_MANAGER
              ROLE_ADMIN:       ROLE_SUPERVISOR


